mod 'puppet-nginx', '3.2.0'
mod 'puppetlabs-concat', '7.0.2'
mod 'puppetlabs-stdlib', '7.1.0'
mod 'puppetlabs-apt', '8.1.0'
mod 'puppetlabs-translate'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker'
